apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripinsights-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: api/userprofile
            port:
              number: 80
      - path: /api/user-java
        pathType: Prefix
        backend:
          service:
            name: api/user-java
            port:
              number: 80
      - path: /api/docs/user-java
        pathType: Prefix
        backend:
          service:
            name: api/user-java
            port:
              number: 80
      - path: /api/trips
        pathType: Prefix
        backend:
          service:
            name: api/trips
            port:
              number: 80
      - path: /api/poi
        pathType: Prefix
        backend:
          service:
            name: api/poi
            port:
              number: 80
      - path: /api/docs/poi
        pathType: Prefix
        backend:
          service:
            name: api/poi
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web/tripviewer
            port:
              number: 80
