apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripinsights-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/user/healthcheck
        pathType: Prefix
        backend:
          service:
            name: userprofile
            port:
              number: 80
      - path: /api/user-java/healthcheck
        pathType: Prefix
        backend:
          service:
            name: user-java
            port:
              number: 80
      - path: /api/trips/healthcheck
        pathType: Prefix
        backend:
          service:
            name: trips
            port:
              number: 80
      - path: /api/poi/healthcheck
        pathType: Prefix
        backend:
          service:
            name: poi
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tripviewer
            port:
              number: 80
