apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Pod
metadata:
  name: tripviewer
  namespace: web
  labels:
    app: tripviewer
spec:
  containers:
    - name: tripviewer
      image: registryolq8408.azurecr.io/tripinsights/tripviewer:1.0
      ports:
        - containerPort: 80
      env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile.api
        - name: TRIPS_API_ENDPOINT
          value: http://trips.api
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: ExternalName
  externalName: tripviewer.web.svc.cluster.local
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
