apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcfservice
  namespace: web
  labels:
    app: wcfservice
    role: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcfservice
  template:
    metadata:
      labels:
        app: wcfservice
        role: web
    spec:
      containers:
        - name: tripviewer
          image: registryolq8408.azurecr.io/wcfservice:1.0
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: wcfservice
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: wcfservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80