kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: poi-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: poi
      role: api
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: web
          role: web