apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: api
type: Opaque
data:
  SQL_SERVER: c3Fsc2VydmVyb2xxODQwOC1lYXN0dXMuZGF0YWJhc2Uud2luZG93cy5uZXQ=
  SQL_PASSWORD: U1FMQWRtaW5AMTIz
  SQL_USER: c3FsYWRtaW5vTHE4NDA4


