apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: poi
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: registryolq8408.azurecr.io/tripinsights/poi:1.0
          ports:
            - containerPort: 80
          env:
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SQL_SERVER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SQL_PASSWORD
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SQL_USER
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-open-hack-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: poi-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: poi
      role: api
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: web
          role: web