apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: trips
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registryolq8408.azurecr.io/tripinsights/trips:1.0
          resources:
              limits:
                cpu: 500m
                memory: 1Gi
          ports:
            - containerPort: 80
          env:
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-secret-vault
                  key: SQL_SERVER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-vault
                  key: SQL_PASSWORD
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-vault
                  key: SQL_USER
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80