apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
  labels:
    app: user-java
    role: api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
        role: api
        version: v1
    spec:
      containers:
        - name: user-java
          image: registryolq8408.azurecr.io/tripinsights/user-java:1.0
          ports:
            - containerPort: 80
          env:
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SQL_SERVER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SQL_PASSWORD
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SQL_USER
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  generation: 1
  labels:
    app: user-java
  name: user-java
  namespace: user-java
spec:
  host: user-java
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: user-java
  name: user-java
  namespace: api
spec:
  gateways:
  - istio-system/general
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /api/user-java
    route:
    - destination:
        host: user-java
        subset: v1
